In [2]:
import numpy as np

In [3]:
"""Задание 1.
Представить фильмы в виде бинарных векторов (numpy array) используюя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

Игра в имитацию [https://www.kinopoisk.ru/film/635772/]
Ярость [https://www.kinopoisk.ru/film/740644/]
12 лет рабства [https://www.kinopoisk.ru/film/606646/]
Однажды в Голливуде [https://www.kinopoisk.ru/film/1047883/]"""


a = np.array([0, 0, 1, 0, 1, 0])
b = np.array([0, 1, 1, 1, 0, 0])
c = np.array([0, 0, 1, 1, 1, 0])
d = np.array([1, 0, 1, 1, 0, 1])

print(a)
print(b)
print(c)
print(d)

[0 0 1 0 1 0]
[0 1 1 1 0 0]
[0 0 1 1 1 0]
[1 0 1 1 0 1]


In [4]:
"""Задание 2.
Вычислить Евклидову норму каждого из векторов, полученных в Задании 1.
"""


a_norm = np.linalg.norm(a)
b_norm = np.linalg.norm(b)
c_norm = np.linalg.norm(c)
d_norm = np.linalg.norm(d)

print(a_norm)
print(b_norm)
print(c_norm)
print(d_norm)

1.4142135623730951
1.7320508075688772
1.7320508075688772
2.0


In [5]:
"""Задание 3.
Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". 
Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов."""


np.arccos(np.dot(b,c)/(np.linalg.norm(b)*np.linalg.norm(c)))

0.8410686705679301

In [15]:
"""Задание 4.
Объединить векторы, полученные в Задании 1 в матрицу, где каждый вектор является строкой матрицы. 
Полученную матрицу умножить на вектор [1,2,3,4]
"""

merged_v = np.array([a,b,c,d])
new_v = np.array([1,2,3,4])
new_v.transpose()@(merged_v)

array([ 4,  2, 10,  9,  4,  4])

In [7]:
"""Вычислить на бумаге и с помощью Python значение первой и второй производной для функции """

'Вычислить на бумаге и с помощью Python значение первой и второй производной для функции '

In [8]:
import sympy as sym

In [9]:
x = sym.Symbol('x')

In [10]:
3*x*(x**2 + x)**3

3*x*(x**2 + x)**3

In [11]:
res=sym.diff(3*x*(x**2+x)**(3),x)
res

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

In [12]:
res.subs(x,1)

132